title: "Intel® 64 and IA-32 Architectures Software Developer’s Manual"
description: "A preview of future Intel® Architecture documentation"
theme: minima
show_excerpts: true
markdown: kramdown

header_pages:
  - faq.md
  - reading-specs.md
  - release-notes.md
  - style_guide.md
  - notices-and-disclaimers.md

icon: "/assets/images/intel-header-logo.png"
icon_link: https://intel.com/
author: Intel Inc.

sdm_html: /SDM/sdm.html

# Note that the following URLs may be hardcoded in raw HTML pages.
survey1: https://forms.office.com/Pages/ResponsePage.aspx?id=iI3JRkTj1E6Elk7XcS4lXWpU_Qd_c_9DpD2_0d9GI6tUNU9KT0FRNVpUNUtEQUwyMktQWk5XRE8wUS4u
public_github: https://github.com/Intel/SDM
